#!/bin/bash
# ==========================================
# Repackage DMG with additional files
# ==========================================
# This script takes the DMG generated by Tauri
# and adds the fix-quarantine.sh and README.txt
# ==========================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DMG_RESOURCES="$PROJECT_DIR/src-tauri/dmg-resources"

# Find the DMG
DMG_DIR="$PROJECT_DIR/src-tauri/target/release/bundle/dmg"
DMG_PATH=$(find "$DMG_DIR" -name "*.dmg" -type f 2>/dev/null | head -1)

if [ -z "$DMG_PATH" ] || [ ! -f "$DMG_PATH" ]; then
    echo "❌ No DMG found. Run 'npm run tauri:build' first."
    exit 1
fi

echo "📦 Found DMG: $DMG_PATH"

# Create temp directories
MOUNT_POINT=$(mktemp -d)
WORK_DIR=$(mktemp -d)

echo "📂 Extracting DMG contents..."

# Mount and copy contents
hdiutil attach "$DMG_PATH" -mountpoint "$MOUNT_POINT" -nobrowse -quiet
cp -R "$MOUNT_POINT"/* "$WORK_DIR/" 2>/dev/null || true
hdiutil detach "$MOUNT_POINT" -quiet

echo "📝 Adding additional files..."

# Copy additional files
cp "$DMG_RESOURCES/fix-quarantine.sh" "$WORK_DIR/"
cp "$DMG_RESOURCES/README.txt" "$WORK_DIR/"

# Make script executable
chmod +x "$WORK_DIR/fix-quarantine.sh"

# Get DMG filename for output
DMG_FILENAME=$(basename "$DMG_PATH")
OUTPUT_DMG="$DMG_DIR/$DMG_FILENAME"

echo "🔨 Creating new DMG..."

# Remove old DMG
rm -f "$DMG_PATH"

# Create new DMG
hdiutil create \
    -volname "awawapp" \
    -srcfolder "$WORK_DIR" \
    -ov \
    -format UDZO \
    "$OUTPUT_DMG"

# Cleanup
rm -rf "$WORK_DIR"
rmdir "$MOUNT_POINT"

echo ""
echo "✅ Done! DMG created: $OUTPUT_DMG"
echo ""
echo "Contents:"
echo "  - awawapp.app"
echo "  - fix-quarantine.sh"
echo "  - README.txt"
